### Register
POST http://localhost:1234/api/register
Content-Type: application/json; charset=utf-8

{
    "username": "John",
    "password": "jhon123",
    "email": "jhon@gmail.com"
}

### Login
POST http://localhost:1234/api/login
Content-Type: application/json; charset=utf-8

{
    "email": "jhon@gmail.com",
    "password": "jhon123"
}

### Logout
POST http://localhost:1234/api/logout

### Profile
GET http://localhost:1234/api/profile