### Register
POST http://localhost:1234/api/register
Content-Type: application/json; charset=utf-8

{
    "username": "Usuario prueba",
    "password": "hola",
    "email": "prueba2@gmail.com"
}

### Login
POST http://localhost:1234/login